return {
    ["auto_medicine"]                = {enabled=false, items={['Antidote']=false,['Eye Drops']=false,['Echo Drops']=false,['Holy Water']=false,['Hallowed Water']=false,['Remedy']=false,['Panacea']=false}},
    ["auto_aftermath"]               = {enabled=false, level=3},
    ["auto_range_weaponskill"]       = {enabled=false, tp=1000, name="Hot Shot"},
    ["auto_melee_weaponskill"]       = {enabled=false, tp=1000, name="Combo"},
    ["weaponskill_limiter"]          = {enabled=false, hpp=10, option=">"},
    ["auto_enmity_generation"]       = {enabled=false, delay=2},
    ["auto_food"]                    = {enabled=false, name=""},
    ["allow_aoe_enmity_spells"]      = false,
    ["auto_one_hours"]               = false,
    ["auto_ranged_attacks"]          = false,
    ["auto_job_abilities"]           = false,
    ["auto_buffing"]                 = false,
    ["auto_debuffing"]               = false,
    ["tank_mode"]                    = false,
    ["nuke_mode"]                    = false,

    ["WAR"] = {
        ["auto_sanguine_blade"]      = {enabled=false, hpp=45},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_provoke"]             = false,
        ["auto_berserk"]             = false,
        ["auto_defender"]            = false,
        ["auto_warcry"]              = false,
        ["auto_aggressor"]           = false,
        ["auto_retaliation"]         = false,
        ["auto_warriors_charge"]     = false,
        ["auto_tomahawk"]            = false,
        ["auto_restraint"]           = false,
        ["auto_blood_rage"]          = false,
        ["auto_mighty_strikes"]      = false,
        ["auto_brazen_rush"]         = false,
    },

    ["MNK"] = {
        ["auto_chakra"]              = {enabled=false, hpp=45},
        ["auto_impetus"]             = false,
        ["auto_footwork"]            = false,
        ["auto_chi_blast"]           = false,
        ["auto_dodge"]               = false,
        ["auto_focus"]               = false,
        ["auto_counterstance"]       = false,
        ["auto_mantra"]              = false,
        ["auto_formless_strikes"]    = false,
        ["auto_perfect_counter"]     = false,
        ["auto_hundred_fists"]       = false,
        ["auto_inner_strength"]      = false,
    },

    ["WHM"] = {
        ["auto_benediction"]         = {enabled=false, mpp=35, targets=3, weight=1800},
        ["auto_martyr"]              = {enabled=false, hpp=45, target=""},
        ["auto_devotion"]            = {enabled=false, mpp=45, target=""},
        ["auto_boost"]               = {enabled=false, name="Boost-STR"},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_status"]              = false,
        ["auto_divine_seal"]         = false,
        ["auto_solace"]              = false,
        ["auto_misery"]              = false,
        ["auto_sacrosanctity"]       = false,
        ["auto_sacrifice"]           = false,
        ["auto_aquaveil"]            = false,
        ["auto_blink"]               = false,
        ["auto_stoneskin"]           = false,
        ["auto_auspice"]             = false,
        ["auto_reraise"]             = false,
        ["auto_repose"]              = false,
        ["auto_asylum"]              = false,
    },

    ["BLM"] = {
        ["auto_spikes"]              = {enabled=false, name="Blaze Spikes"},
        ["auto_cascade"]             = {enabled=false, target="", tp=1000},
        ["auto_drain"]               = {enabled=false, hpp=55},
        ["auto_aspir"]               = {enabled=false, mpp=55},
        ["auto_myrkr"]               = {enabled=false, mpp=45},
        ["auto_elemental_seal"]      = false,
        ["auto_mana_wall"]           = false,
        ["auto_enmity_douse"]        = false,
        ["auto_manawell"]            = false,
        ["auto_sleep"]               = false,
        ["auto_sleepga"]             = false,
        ["auto_manafont"]            = false,
        ["auto_subtle_sorcery"]      = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["RDM"] = {
        ["auto_enspell"]             = {enabled=false, name="Enfire"},
        ["auto_spikes"]              = {enabled=false, name="Blaze Spikes"},
        ["auto_gain"]                = {enabled=false, name="Gain-DEX"},
        ["auto_convert"]             = {enabled=false, mpp=55, hpp=55},
        ["auto_sanguine_blade"]      = {enabled=false, hpp=55},
        ["auto_composure"]           = false,
        ["auto_saboteur"]            = false,
        ["auto_spontaneity"]         = false,
        ["auto_blink"]               = false,
        ["auto_aquaveil"]            = false,
        ["auto_stoneskin"]           = false,
        ["auto_haste"]               = false,
        ["auto_phalanx"]             = false,
        ["auto_temper"]              = false,
        ["auto_refresh"]             = false,
        ["auto_dispel"]              = false,
        ["auto_sleep"]               = false,
        ["auto_chainspell"]          = false,
        ["auto_stymie"]              = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["THF"] = {
        ["auto_steal"]               = false,
        ["auto_sneak_attack"]        = false,
        ["auto_trick_attack"]        = false,
        ["auto_mug"]                 = false,
        ["auto_assassins_charge"]    = false,
        ["auto_feint"]               = false,
        ["auto_despoil"]             = false,
        ["auto_conspirator"]         = false,
        ["auto_bully"]               = false,
        ["auto_saws"]                = false,
        ["auto_taws"]                = false,
        ["auto_perfect_dodge"]       = false,
        ["auto_larceny"]             = false,
    },

    ["PLD"] = {
        ["auto_chivalry"]            = {enabled=false, mpp=55, tp=1500},
        ["auto_cover"]               = {enabled=false, target=""},
        ["auto_sanguine_blade"]      = {enabled=false, hpp=55},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_divine_emblem"]       = false,
        ["auto_holy_circle"]         = false,
        ["auto_shield_bash"]         = false,
        ["auto_sentinel"]            = false,
        ["auto_rampart"]             = false,
        ["auto_majesty"]             = false,
        ["auto_fealty"]              = false,
        ["auto_sepulcher"]           = false,
        ["auto_palisade"]            = false,
        ["auto_flash"]               = false,
        ["auto_reprisal"]            = false,
        ["auto_phalanx"]             = false,
        ["auto_crusade"]             = false,
        ["auto_enlight"]             = false,
        ["auto_invincible"]          = false,
        ["auto_intervene"]           = false,
    },

    ["DRK"] = {
        ["auto_dark_seal"]           = {enabled=false, name="Drain III"},
        ["auto_absorb"]              = {enabled=false, name="Absorb-ACC"},
        ["auto_drain"]               = {enabled=false, hpp=55},
        ["auto_aspir"]               = {enabled=false, mpp=55},
        ["auto_sanguine_blade"]      = {enabled=false, hpp=55},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_arcane_circle"]       = false,
        ["auto_last_resort"]         = false,
        ["auto_weapon_bash"]         = false,
        ["auto_souleater"]           = false,
        ["auto_consume_mana"]        = false,
        ["auto_diabolic_eye"]        = false,
        ["auto_nether_void"]         = false,
        ["auto_arcane_crest"]        = false,
        ["auto_scarlet_delirium"]    = false,
        ["auto_dread_spikes"]        = false,
        ["auto_endark"]              = false,
        ["auto_blood_weapon"]        = false,
        ["auto_soul_enslavement"]    = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["BST"] = {
        ["auto_reward"]              = {enabled=false, hpp=55},
        ["auto_ready"]               = {enabled=false, moves=""},
        ["auto_call_beast"]          = false,
        ["auto_bestial_loyalty"]     = false,
        ["auto_killer_instinct"]     = false,
        ["auto_fight"]               = false,
        ["auto_snarl"]               = false,
        ["auto_spur"]                = false,
        ["auto_run_wild"]            = false,
        ["auto_unleash"]             = false,
    },

    ["BRD"] = {
        ["auto_foe_lullaby"]         = false,
        ["auto_horde_lullaby"]       = false,
        ["auto_finale"]              = false,
    },

    ["RNG"] = {
        ["auto_decoy_shot"]          = {enabled=false, target=""},
        ["auto_sharpshot"]           = false,
        ["auto_scavenge"]            = false,
        ["auto_camouflage"]          = false,
        ["auto_barrage"]             = false,
        ["auto_velocity_shot"]       = false,
        ["auto_unlimited_shot"]      = false,
        ["auto_flashy_shot"]         = false,
        ["auto_stealth_shot"]        = false,
        ["auto_double_shot"]         = false,
        ["auto_bounty_shot"]         = false,
        ["auto_hover_shot"]          = false,
        ["auto_eagle_eye_shot"]      = false,
        ["auto_overkill"]            = false,
    },

    ["SMN"] = {
        ["auto_summon"]              = {enabled=false, name="Carbuncle"},
        ["auto_bp_rage"]             = {enabled=false, pacts={["Ifrit"]="Flaming Crush"}},
        ["auto_bp_ward"]             = {enabled=false, pacts={["Ifrit"]="Crimson Howl"}},
        ["auto_myrkr"]               = {enabled=false, mpp=45},
        ["auto_elemental_siphon"]    = {enabled=false, mpp=55},
        ["auto_apogee"]              = false,
        ["auto_mana_cede"]           = false,
        ["auto_assault"]             = false,
        ["auto_rotate"]              = false,
        ["auto_pact_magic_burst"]    = false,
        ["auto_astral_flow"]         = false,
        ["auto_astral_conduit"]      = false,
    },

    ["SAM"] = {
        ["auto_shikikoyo"]           = {enabled=false, tp=1500, target=""},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_warding_circle"]      = false,
        ["auto_third_eye"]           = false,
        ["auto_hasso"]               = false,
        ["auto_meditate"]            = false,
        ["auto_seigan"]              = false,
        ["auto_sekkanoki"]           = false,
        ["auto_konzen_ittai"]        = false,
        ["auto_blade_bash"]          = false,
        ["auto_sengikori"]           = false,
        ["auto_hamanoha"]            = false,
        ["auto_hagakure"]            = false,
        ["auto_meikyo_shisui"]       = false,
        ["auto_yaegasumi"]           = false,
    },

    ["NIN"] = {
        ["auto_yonin"]               = false,
        ["auto_innin"]               = false,
        ["auto_sange"]               = false,
        ["auto_futae"]               = false,
        ["auto_issekigan"]           = false,
        ["auto_utsusemi"]            = false,
        ["auto_myoshu"]              = false,
        ["auto_migawari"]            = false,
        ["auto_gekka"]               = false,
        ["auto_yain"]                = false,
        ["auto_kakka"]               = false,
        ["auto_mikage"]              = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["DRG"] = {
        ["auto_restoring_breath"]    = {enabled=false, hpp=55},
        ["auto_call_wyvern"]         = false,
        ["auto_ancient_circle"]      = false,
        ["auto_jump"]                = false,
        ["auto_high_jump"]           = false,
        ["auto_super_jump"]          = false,
        ["auto_spirit_jump"]         = false,
        ["auto_soul_jump"]           = false,
        ["auto_angon"]               = false,
        ["auto_dragon_breaker"]      = false,
        ["auto_deep_breathing"]      = false,
        ["auto_smiting_breath"]      = false,
        ["auto_steady_wing"]         = false,
        ["auto_spirit_surge"]        = false,
        ["auto_fly_high"]            = false,
    },

    ["BLU"] = {
        ["auto_diffusion"]           = {enabled=false, name="Mighty Guard"},
        ["auto_unbridled_wisdom"]    = {enabled=false, mode=1},
        ["auto_unbridled_learning"]  = {enabled=false, mode=1},
        ["auto_sanguine_blade"]      = {enabled=false, hpp=55},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_magic_hammer"]        = false,
        ["auto_burst_affinity"]      = false,
        ["auto_chain_affinity"]      = false,
        ["auto_convergence"]         = false,
        ["auto_efflux"]              = false,
        ["auto_sleepga"]             = false,
        ["auto_azure_lore"]          = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["COR"] = {
        ["auto_rolls"]               = {enabled=false, max=2, list={"Chaos Roll","Samurai Roll"}},
        ["auto_quick_draw"]          = {enabled=false, name="Light Shot"},
        ["auto_double_up"]           = {enabled=false, max=7},
        ["auto_crooked_cards"]       = false,
        ["auto_random_deal"]         = false,
        ["auto_triple_shot"]         = false,
        ["auto_wild_card"]           = false,
        ["auto_cutting_cards"]       = false,
    },

    ["PUP"] = {
        ["auto_maneuvers"]           = {enabled=false, list={"Fire Maneuver","Light Maneuver","Wind Maneuver"}},
        ["auto_secondary_maneuvers"] = {enabled=false, list={"Fire Maneuver","Light Maneuver","Wind Maneuver"}, hpp=40},
        ["auto_repair"]              = {enabled=false, hpp=55},
        ["auto_activate"]            = false,
        ["auto_cooldown"]            = false,
        ["auto_deploy"]              = false,
        ["auto_deploy_on_aggro"]     = false,
        ["auto_target_on_aggro"]     = false,
        ["auto_assist_master"]       = false,
        ["dad_method_enabled"]       = false,
        ["auto_overdrive"]           = false,
        ["auto_heady_artifice"]      = false,
    },

    ["DNC"] = {
        ["auto_sambas"]              = {enabled=false, name="Haste Samba"},
        ["auto_steps"]               = {enabled=false, name="Quickstep"},
        ["auto_animated_flourish"]   = false,
        ["auto_violent_flourish"]    = false,
        ["auto_reverse_flourish"]    = false,
        ["auto_building_flourish"]   = false,
        ["auto_wild_flourish"]       = false,
        ["auto_climactic_flourish"]  = false,
        ["auto_striking_flourish"]   = false,
        ["auto_ternary_flourish"]    = false,
        ["auto_contradance"]         = false,
        ["auto_saber_dance"]         = false,
        ["auto_fan_dance"]           = false,
        ["auto_no_foot_rise"]        = false,
        ["auto_presto"]              = false,
        ["auto_trance"]              = false,
        ["auto_grand_pas"]           = false,
    },

    ["SCH"] = {
        ["auto_stratagems"]          = {enabled=false, list={penury={}, celerity={}, accession={}, rapture={}, perpetuance={}, parsimony={}, alacrity={}, manifestation={}, ebullience={}}},
        ["auto_embrava"]             = {enabled=false, target=""},
        ["auto_spikes"]              = {enabled=false, name="Blaze Spikes"},
        ["auto_storms"]              = {enabled=false, name="Firestorm"},
        ["auto_schchain"]            = {enabled=false, mode="Fusion"},
        ["auto_sublimation"]         = {enabled=false, mpp=65},
        ["auto_drain"]               = {enabled=false, hpp=55},
        ["auto_aspir"]               = {enabled=false, mpp=55},
        ["auto_myrkr"]               = {enabled=false, mpp=45},
        ["auto_status"]              = false,
        ["auto_light_arts"]          = false,
        ["auto_addendum"]            = false,
        ["auto_modus_veritas"]       = false,
        ["auto_enlightenment"]       = false,
        ["auto_aquaveil"]            = false,
        ["auto_blink"]               = false,
        ["auto_stoneskin"]           = false,
        ["auto_tabula_rasa"]         = false,
        ["auto_kaustra"]             = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["GEO"] = {
        ["auto_bubbles"]             = {enabled=false, list={"Indi-Fury","Geo-Frailty","Indi-Haste"}},
        ["auto_full_circle"]         = {enabled=false, distance=22},
        ["auto_drain"]               = {enabled=false, hpp=55},
        ["auto_aspir"]               = {enabled=false, mpp=55},
        ["auto_radial_arcana"]       = {enabled=false, mpp=55},
        ["auto_mending_halation"]    = {enabled=false, hpp=55},
        ["auto_life_cycle"]          = {enabled=false, hpp=55},
        ["auto_moonlight"]           = {enabled=false, mpp=45},
        ["auto_theurgic_focus"]      = false,
        ["auto_lasting_emanation"]   = false,
        ["auto_ecliptic_attrition"]  = false,
        ["auto_blaze_of_glory"]      = false,
        ["auto_dematerialize"]       = false,
        ["auto_indicolure"]          = false,
        ["auto_geocolure"]           = false,
        ["auto_entrust"]             = false,
        ["auto_bolster"]             = false,
        ["auto_widened_compass"]     = false,
        ["auto_nukes"]               = {enabled=false, delay=1, list={}},
    },

    ["RUN"] = {
        ["auto_spikes"]              = {enabled=false, name="Blaze Spikes"},
        ["auto_runes"]               = {enabled=false, list={"Ignis","Ignis","Ignis"}},
        ["auto_vivacious_pulse"]     = {enabled=false, hpp=55, mpp=55},
        ["auto_embolden"]            = {enabled=false, name="Temper"},
        ["auto_sanguine_blade"]      = {enabled=false, hpp=55},
        ["auto_vallation"]           = false,
        ["auto_swordplay"]           = false,
        ["auto_swipe"]               = false,
        ["auto_lunge"]               = false,
        ["auto_pflug"]               = false,
        ["auto_valiance"]            = false,
        ["auto_gambit"]              = false,
        ["auto_battuta"]             = false,
        ["auto_rayke"]               = false,
        ["auto_liement"]             = false,
        ["auto_one_for_all"]         = false,
        ["auto_aquaveil"]            = false,
        ["auto_blink"]               = false,
        ["auto_stoneskin"]           = false,
        ["auto_temper"]              = false,
        ["auto_flash"]               = false,
        ["auto_foil"]                = false,
        ["auto_refresh"]             = false,
        ["auto_phalanx"]             = false,
        ["auto_regen"]               = false,
        ["auto_crusade"]             = false,
        ["auto_elemental_sforzo"]    = false,
        ["auto_odyllic_subterfuge"]  = false,
    },

}